from bunch import Bunch

CONFIG = Bunch(dict(
    SPLIT_SEED=0,
    IMAGE_TARGET_HEIGHT=240,
    IMAGE_TARGET_WIDTH=180,
    EPOCHS=15,
    BATCH_SIZE=256,
    SHUFFLE_BUFFER_SIZE=2560,
    NORMALIZATION_VALUE=256,
    LEARNING_RATE=1e-5,
    TUNE_EPOCHS=10,
))
